package eu.blockup.GlobalChestShop.Util.Statements;

public class  Permissions{

	
	//<-------------------- Player -------------------->
	
	public final static String PLAYER_CREATE_CHEST_SHOP = "GLOBALCHESTSHOP.PLAYER.CREATE_CHEST_SHOP";
	public final static String PLAYER_VISIT_OTHER_PLAYERS_SHOPS = "GLOBALCHESTSHOP.PLAYER.VISIT_OTHER_PLAYERS_SHOPS";
	public final static String PLAYER_OPEN_GLOBAL_SHOPS = "GLOBALCHESTSHOP.PLAYER.OPEN_GLOBAL_SHOPS";
	public final static String PLAYER_OPEN_ADMIN_SHOP = "GLOBALCHESTSHOP.PLAYER.OPEN_ADMIN_SHOP";
	public final static String PLAYER_BUY_FROM_ADMINSHOP = "GLOBALCHESTSHOP.PLAYER.BUY_FROM_ADMINSHOP";
	public final static String PLAYER_SELL_TO_ADMINSHOP = "GLOBALCHESTSHOP.PLAYER.SELL_TO_ADMINSHOP";
	
	
	//<-------------------- VIP -------------------->
	
	public final static String VIP_OPEN_GLOBALSHOP_BY_COMMAND = "GLOBALCHESTSHOP.VIP.OPEN_GLOBALSHOP_BY_COMMAND";
	public final static String VIP_CREATE_NEW_AUCTIONS_INSIDE_GLOBALSHOP_COMMAND = "GLOBALCHESTSHOP.VIP.CREATE_NEW_AUCTIONS_INSIDE_GLOBALSHOP_COMMAND";
	public final static String VIP_CREATE_NEW_AUCTIONS_INSIDE_BUY_COMMAND = "GLOBALCHESTSHOP.VIP.CREATE_NEW_AUCTIONS_INSIDE_BUY_COMMAND";
	public final static String VIP_BUY_COMMAND = "GLOBALCHESTSHOP.VIP.BUY_COMMAND";
	public final static String VIP_SELL_COMMAND = "GLOBALCHESTSHOP.VIP.SELL_COMMAND";
	public final static String VIP_SELL_EXCEED_ADMOUNT_OF_AUCTION = "GLOBALCHESTSHOP.VIP.EXCEED_AUCTION_LIMIT";
	
	

	
	//<-------------------- Moderator -------------------->
	
	public final static String MODERATOR_SEE_PLAYERS_SHOPS = "GLOBALCHESTSHOP.MODERATOR.SEE_PLAYERS_SHOPS";
	public final static String MODERATOR_DELETE_AUCTIONS = "GLOBALCHESTSHOP.MODERATOR.DELETE_AUCTIONS";
	
	
	//<-------------------- Admin -------------------->
	
	public final static String ADMIN = "GLOBALCHESTSHOP.ADMIN";
}

