#     _____ _       _           _  _____ _               _    _____ _                 
#    / ____| |     | |         | |/ ____| |             | |  / ____| |                
#   | |  __| | ___ | |__   __ _| | |    | |__   ___  ___| |_| (___ | |__   ___  _ __  
#   | | |_ | |/ _ \| '_ \ / _` | | |    | '_ \ / _ \/ __| __|\___ \| '_ \ / _ \| '_ \ 
#   | |__| | | (_) | |_) | (_| | | |____| | | |  __/\__ \ |_ ____) | | | | (_) | |_) |
#    \_____|_|\___/|_.__/ \__,_|_|\_____|_| |_|\___||___/\__|_____/|_| |_|\___/| .__/ 
#                                                                              | |    
#                                                                              |_|  
MySQL:
  host: localhost
  port: 3306
  database: GlobalChestShop
  user: root
  password: ''
  tablePrefix: 'GCS_'
Appearance:
  Sign:
    localChestShop: '&a[LocalShop]'
    globalChestShop: '&a[GlobalShop]'
    adminShop: '&a[AdminShop]'
    seconLineColor: '&2'
    AllItems:
      signFooter: AllItems
      displayItem: COMPASS
  buyButton: 'sign'
  sellButton: SIGN
  amountButton: 'anvil'
  closeButton: 'red_stained_glass_pane'
  background: 'black_stained_glass_pane'
  showAuctionCountByAmount: false
Other:
  showAdminshopsInsideGlobalShops: true
  amountOfLocalChestShopsPerPlayer: 1
  escButtonLeadsToPreviousWindow: true
Money:
  tax: 5.0%
